##### Lavatrice

- alias: Actionable. Lavatrice Svuotata?
  trigger:
    platform: state
    entity_id: input_boolean.lavatrice_da_scaricare
    to: 'on'
    for:
      minutes: 5
  action:
    - alias: Repeat the sequence UNTIL the conditions are true
      repeat:
        sequence:
          # Run command that for some reason doesn't always work
          - service: script.activate_alexa_actionable_notification
            data_template:
              text: "La lavatrice ha finito ma non risulta svuotata. Vuoi che la segni io come svuotata?"
              event_id: 'actionable_notification_lavatrice_svuotata'
              alexa_device: '{{ states.sensor.last_alexa.state }}'
          # Give it time to complete
          - delay:
              minutes: 15
        until:
          # Did it work?
          - condition: state
            entity_id: input_boolean.lavatrice_da_scaricare
            state: 'off'


- alias: Actionable. Lavatrice, Svuotala.
  trigger:
    platform: event
    event_type: alexa_actionable_notification
    event_data:
      event_id: actionable_notification_lavatrice_svuotata
      event_response_type: ResponseYes
  action:
    - service: alexa_media.update_last_called #this will force update the last Alexa attribute used by the sensor
    - delay: 00:00:01 # you may need to increase this value if you dont get the response on the echo you asked the question
    - service: notify.alexa_media
      data_template:
        target:
          -  '{{ states.sensor.last_alexa.state }}'
        message: "Fatto! Lavatrice scaricata."
        data:
          type: announce
          method: all # or speak or show
    - service: notify.telegram_1
      data_template:
        message: ":sweat_drops: La lavatrice é stata scaricata.**"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.lavatrice_da_scaricare


- alias: Actionable. Lavatrice, No.
  trigger:
    platform: event
    event_type: alexa_actionable_notification
    event_data:
      event_id: actionable_notification_lavatrice_svuotata
      event_response_type: ResponseNo
  action:
    - service: alexa_media.update_last_called #this will force update the last Alexa attribute used by the sensor
    - delay: 00:00:01 # you may need to increase this value if you dont get the response on the echo you asked the question
    - service: notify.alexa_media
      data_template:
        target:
          -  '{{ states.sensor.last_alexa.state }}'
        message: "Allora te lo chiederó ancora tra 15 minuti, se nessuno la svuoterà nel frattempo."
        data:
          type: announce
          method: all # or speak or show


- alias: Actionable. Lavatrice, None.
  trigger:
    platform: event
    event_type: alexa_actionable_notification
    event_data:
      event_id: actionable_notification_lavatrice_svuotata
      event_response_type: ResponseNone
  action:
    - service: alexa_media.update_last_called #this will force update the last Alexa attribute used by the sensor
    - delay: 00:00:01 # you may need to increase this value if you dont get the response on the echo you asked the question
    - service: notify.alexa_media
      data_template:
        target:
          -  '{{ states.sensor.last_alexa.state }}'
        message: "Non mi rispondi? Te lo chiederó ancora tra 15 minuti, se nessuno la svuoterà nel frattempo."
        data:
          type: announce
          method: all # or speak or show
